[package]
name = "SurrealDB"
version = "0.1.0"
edition = "2021"

[dependencies]
faker_rand = "0.1.1"
rand = "0.9.0"
rocket = { version = "0.5.1", features = ["json","secrets"] }
serde = { version = "1.0.209", features = ["derive"] }
surrealdb = "2.0.4"
thiserror = "2.0.11"